services:
    app.role_service:
        class: AppBundle\Service\RoleService
        arguments: ['@doctrine.orm.entity_manager',"@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Role')"]
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
